set dotenv-load

default:
  @just --list

apply:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu init
  tofu apply

destroy:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu destroy

destroy-only node:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu init
  tofu destroy --target 'module.proxmox_node["{{node}}"]'

dns-flush-cache domain:
  #!/usr/bin/env sh
  set -euo pipefail
  for node in $(cat vars.secrets.yaml | yq -r '.nodes | keys | .[]')
  do
    IPV6="fd74:6a6f::$(cat vars.secrets.yaml | yq -r ".nodes[\"${node}\"].id")"
    ssh -J root@nevaroo-proxmox-cloud-internal root@${IPV6} 'unbound-control flush_negative' | ts ${node}
    ssh -J root@nevaroo-proxmox-cloud-internal root@${IPV6} 'unbound-control flush_zone {{domain}}' | ts ${node}
  done

configure node tag="":
  #!/usr/bin/env sh
  cd {{source_directory()}}/ansible
  export VERSION=$(git describe --tags --always --dirty)
  TAGS=""; if [ -n "{{tag}}" ]; then TAGS="--tags {{tag}}"; fi
  ansible-playbook \
    --extra-vars "@{{source_directory()}}/../global.yaml" \
    --extra-vars "tjo_cloud_version=${VERSION}" \
    --inventory inventory.yaml \
    $TAGS \
    playbook.yaml --limit {{node}}

configure-all tag="":
  #!/usr/bin/env sh
  cd {{source_directory()}}/ansible
  export VERSION=$(git describe --tags --always --dirty)
  TAGS=""; if [ -n "{{tag}}" ]; then TAGS="--tags {{tag}}"; fi
  ansible-playbook \
    --extra-vars "@{{source_directory()}}/../global.yaml" \
    --extra-vars "tjo_cloud_version=${VERSION}" \
    --inventory inventory.yaml \
    $TAGS \
    playbook.yaml

ssh node:
  ssh bine@{{node}}-network-cloud-internal -p 2222
