- name: FIREWALL - Define internal zone
  ansible.posix.firewalld:
    source: '{{ item }}'
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ tjo_cloud_networks }}"
  tags: firewall

- name: FIREWALL - Allow SSH, HTTP, HTTPS, ZEROTIER and HEALTHCHECK
  ansible.posix.firewalld:
    port: '{{ item }}'
    zone: public
    permanent: true
    immediate: true
    state: enabled
  loop:
    - '22/tcp'
    - '80/tcp'
    - '443/tcp'
    - '9993/udp' # Zerotier
    - '1337/tcp' # Healthcheck
  tags: firewall

- name: FIREWALL - Allow SSH
  ansible.posix.firewalld:
    service: ssh
    zone: '{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  loop:
    - 'internal'
    - 'public'
  tags: firewall
