- name: Remove zerotier
  ansible.builtin.apt:
    name: zerotier-one
    state: absent
  tags: config-reload

- name: Setup wireguard
  ansible.builtin.import_role:
    name: network-tjo-cloud-peer
    tasks_from: "setup"
  tags: config-reload

- name: Setup Network Wireguard and BGP peer
  ansible.builtin.import_role:
    name: network-tjo-cloud-peer
    tasks_from: "configure"
  vars:
    cfg:
      id: "{{ wireguard.id }}"
      wireguard_address: "{{ wireguard.address }}"
      wireguard_pre_shared_key: "{{ wireguard_pre_shared_key }}"
      peers:
        - name: "nevaroo"
          id: 10
          wireguard_endpoint: "2a01:4f8:120:7700::3"
          wireguard_address: "fd74:6a6f:3030:70::10/128"
          wireguard_public_key: "o/ia1z+qixUF5j/H/WFicI+djGzLUeUnz7LdDfaygVw="
        - name: "endor"
          id: 11
          #wireguard_endpoint: "2001:2043:5d5d:d300:a8bb:ff:fe00:dbea"
          wireguard_address: "fd74:6a6f:3030:70::11/128"
          wireguard_public_key: "UE2MeFP9mzfywxwiqOENJ7cO7wGX9iytTw3jpb41cns="
        - name: "batuu"
          id: 12
          #wireguard_endpoint: "2001:2043:5d5d:d300:a8bb:ff:fe00:f737"
          wireguard_address: "fd74:6a6f:3030:70::12/128"
          wireguard_public_key: "+wXJ1spUAGtN+hePGFewNYW7mB+OxkVHesJigeQ6cEY="
        - name: "jakku"
          id: 13
          #wireguard_endpoint: "2001:2043:5d5d:d300:a8bb:ff:fe00:8aaf"
          wireguard_address: "fd74:6a6f:3030:70::13/128"
          wireguard_public_key: "h/7sAo+5xyhs01/6PyOcbEIHQ0B6mSsdP++Oa1z8jig="
  tags: config-reload

- name: Refresh facts
  ansible.builtin.setup:
    gather_subset:
      - network

- name: Add repository
  ansible.builtin.deb822_repository:
    name: haproxy
    types: deb
    uris: https://haproxy.debian.net
    suites: trixie-backports-3.3
    components: main
    signed_by: https://haproxy.debian.net/haproxy-archive-keyring.gpg
    install_python_debian: yes

- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Copy Haproxy configs
  ansible.builtin.template:
    src: 'root{{ item }}'
    dest: '{{item}}'
    mode: '0644'
    owner: "root"
    group: "root"
  notify: Restart haproxy
  loop:
    - "/etc/haproxy/blocked-bad-crawlers.acl"
    - "/etc/haproxy/blocked-manual.acl"
    - "/etc/haproxy/domains.map"
    - "/etc/haproxy/haproxy.cfg"
  tags: config-reload

- name: Prepare GeoIP directory
  ansible.builtin.file:
    state: directory
    path: "/usr/share/geoip"
    mode: "0755"
    owner: "root"
    group: "root"
  tags: config-reload

- name: Copy GeoIP data
  ansible.builtin.copy:
    src: 'root{{ item }}'
    dest: '{{item}}'
    mode: '0644'
    owner: "root"
    group: "root"
  notify: Restart alloy
  loop:
    - "/usr/share/geoip/GeoLite2-ASN.mmdb"
    - "/usr/share/geoip/GeoLite2-City.mmdb"
  tags: config-reload

- name: Enable and start haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
