- name: Copy systemd files
  ansible.builtin.copy:
    src: "../root{{ item }}"
    dest: "{{ item }}"
    mode: '0644'
    owner: "root"
    group: "root"
  loop:
    - '/etc/systemd/system/notify-webhook-failure@.service'
    - '/etc/systemd/system/notify-webhook-success@.service'

- name: Copy binary
  ansible.builtin.copy:
    src: "../root/usr/local/bin/notify-webhook"
    dest: "/usr/local/bin/notify-webhook"
    mode: '0711'
    owner: "root"
    group: "root"
