on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: nix-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: false
          skip-nix-installation: true
          extra-nix-config: access-tokens = github.com=${{ secrets.NIX_GITHUB_TOKEN }}

      - run: devbox run -- just lint
