on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.NIX_GITHUB_TOKEN }}
        with:
          enable-cache: false
          github-token: "${{ secrets.NIX_GITHUB_TOKEN }}"

      - run: devbox run -- just lint
