on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetify-com/devbox-install-action@060be5a8f69feff899b73193cadfcaacd5b88310
        env:
          GITHUB_TOKEN: ""
        with:
          enable-cache: true

      - run: devbox run -- just lint
