- name: Add repository
  ansible.builtin.deb822_repository:
    name: netbird
    types: deb
    uris: https://pkgs.netbird.io/debian
    suites: stable
    components: main
    signed_by: https://pkgs.netbird.io/debian/public.key
    install_python_debian: yes

- name: Install Netbird
  ansible.builtin.apt:
    name: netbird
    state: present
    update_cache: yes
