geoip2 /var/geoip.mmdb {
  $geoip2_data_country_iso_code country iso_code;
  $geoip2_data_latitude         location latitude;
  $geoip2_data_longitude        location longitude;
}

log_format geoip_with_upstream 'country=$geoip2_data_country_iso_code '
                 'lat=$geoip2_data_latitude '
                 'long=$geoip2_data_longitude '
                 'ip=$remote_addr '
                 'protocol=$protocol '
                 'server_name=$ssl_preread_server_name '
                 'server_port=$server_port '
                 'upstream=$selected_upstream '
                 'status=$status '
                 'bytes_sent=$bytes_sent '
                 'bytes_received=$bytes_received '
                 'session_time=$session_time';

log_format geoip 'country=$geoip2_data_country_iso_code '
                 'lat=$geoip2_data_latitude '
                 'long=$geoip2_data_longitude '
                 'ip=$remote_addr '
                 'protocol=$protocol '
                 'server_port=$server_port '
                 'status=$status '
                 'bytes_sent=$bytes_sent '
                 'bytes_received=$bytes_received '
                 'session_time=$session_time';
