default:
  @just --list

apply:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu init -upgrade
  tofu apply

destroy:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu  destroy

configure tag="":
  #!/usr/bin/env sh
  cd {{source_directory()}}/ansible
  export VERSION=$(git describe --tags --always --dirty)
  TAGS=""; if [ -n "{{tag}}" ]; then TAGS="--tags {{tag}}"; fi
  ansible-playbook \
    --extra-vars "@{{source_directory()}}/../global.yaml" \
    --extra-vars "tjo_cloud_version=${VERSION}" \
    --inventory inventory.yaml \
    $TAGS \
    playbook.yaml

ssh:
  ssh bine@fd7a:115c:a1e0::9638:6035 -p 22

wake:
  # Jakku
  ssh bine@fd7a:115c:a1e0::9638:6035 -p 22 'wakeonlan 00:1e:06:45:0c:35'
  # Endor
  ssh bine@fd7a:115c:a1e0::9638:6035 -p 22 'wakeonlan 00:1e:06:45:5d:c9'
  # Batuu
  ssh bine@fd7a:115c:a1e0::9638:6035 -p 22 'wakeonlan 00:1e:06:45:5e:d1'
