- name: Add Grafana repository
  block:
    - name: Fetch key
      ansible.builtin.get_url:
        url: https://apt.grafana.com/gpg.key
        dest: /etc/apt/keyrings/grafana.asc
        checksum: sha256:3d4029689bc7e4444ec00abafa07f21e9c812b41f1123ab5bbe6f8c3e3f7ff8c

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main
        state: present

- name: Install Grafana Alloy
  ansible.builtin.apt:
    name: alloy
    state: present
    update_cache: yes
