- name: Add Caddy repository
  block:
    - name: Fetch key
      ansible.builtin.get_url:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        dest: /etc/apt/keyrings/caddy.asc
        checksum: sha256:5791c2fb6b6e82feb5a69834dd2131f4bcc30af0faec37783b2dc1c5c224a82a

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
        state: present

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: yes
