- name: UFW - Install
  ansible.builtin.apt:
    name: ufw
    state: present

- name: UFW - Allow HTTP and HTTPS
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '80'
    - '443'
  # TODO: Only when kind = gateway

- name: UFW - Allow S3 API, S3 WEB and RPC ports
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
    src: '10.0.0.0/16'
  loop:
    - '3900'
    - '3902'
    - '3901'

- name: UFW - Allow SSH
  community.general.ufw:
    rule: allow
    port: '2222'
    proto: tcp

- name: UFW - Enable and deny by default
  community.general.ufw:
    state: enabled
    default: deny
