- name: FIREWALL - Define internal zone
  ansible.posix.firewalld:
    source: '{{ item }}'
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ tjo_cloud_networks }}"
  tags: firewall

- name: FIREWALL - Allow S3 API, S3 WEB, RPC and ADMIN ports
  ansible.posix.firewalld:
    port: '{{ item }}'
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop:
    - "3900/tcp"
    - "3902/tcp"
    - "3901/tcp"
    - "3903/tcp"
  tags: firewall

- name: FIREWALL - Allow SSH
  ansible.posix.firewalld:
    service: ssh
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  tags: firewall
