- name: Check if garage is already installed
  ansible.builtin.stat:
    name: "/usr/local/bin/garage"
  register: garage_binary_stat

- name: Get current Garage version
  ansible.builtin.command:
    cmd: "/usr/local/bin/garage node --version"
  changed_when: false
  register: garage_version_output
  when: garage_binary_stat.stat.exists

- name: Set current Garage version fact
  ansible.builtin.set_fact:
    current_garage_version: "{{ garage_version_output.stdout.split(' ')[-1] }}"
  when: garage_binary_stat.stat.exists and garage_version_output.rc == 0

- name: Check if Garage version is older
  ansible.builtin.fail:
    msg: "Garage version {{ garage_version }} is older than the current version {{ current_garage_version }}."
  when: current_garage_version is defined and current_garage_version is version(garage_version, '>')
