- name: Gateway - Firewall
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '80'
    - '443'
    - '9993' # Zerotier

- name: Install Zerotier
  ansible.builtin.include_role:
    name: zerotier

- name: Configure Zerotier
  ansible.builtin.shell: |
    systemctl stop zerotier-one
    echo "{{ tjo_cloud_metadata.zerotier.public_key }}" >/var/lib/zerotier-one/identity.public
    echo "{{ tjo_cloud_metadata.zerotier.private_key }}" >/var/lib/zerotier-one/identity.secret
    systemctl start zerotier-one
    sleep 5
    zerotier-cli join b6079f73c6379990
  args:
    creates: /var/lib/zerotier-one/networks.d/b6079f73c6379990.conf

- name: Refresh facts
  ansible.builtin.setup:
    gather_subset:
      - network

- name: Install Caddy
  ansible.builtin.include_role:
    name: caddy
