- name: Install and Configure Firewall
  ansible.builtin.include_tasks:
    file: firewall.yaml

- name: Install Alloy
  ansible.builtin.include_tasks:
    file: alloy_install.yaml

- name: Install Zerotier
  ansible.builtin.include_tasks:
    file: alloy_install.yaml

- name: Install Caddy
  ansible.builtin.include_tasks:
    file: caddy_install.yaml
  # TODO: Only when kind = gateway

- name: Check garage version
  ansible.builtin.include_tasks:
    file: check_garage_version.yml

- name: Upgrade Garage
  ansible.builtin.include_tasks:
    file: garage_install.yaml
  when: current_garage_version is defined and current_garage_version is version(garage_version, '<')
  throttle: 1

- name: Install Garage
  ansible.builtin.include_tasks:
    file: garage_install.yaml
  when: current_garage_version is not defined or not (current_garage_version is defined and current_garage_version == garage_version)

- name: Configure Garage
  ansible.builtin.include_tasks:
    file: garage_configure.yaml
