- name: Copy disable-network-offloading@ systemd file
  ansible.builtin.template:
    src: "root/etc/systemd/system/disable-network-offloading@.service"
    dest: "/etc/systemd/system/disable-network-offloading@.service"
    mode: "0644"
    owner: "root"
    group: "root"

- name: Start and enable disable-network-offloading service
  ansible.builtin.systemd:
    name: "disable-network-offloading@{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ features.disable_network_offloading.interfaces }}"
