- name: Install SDN Dependencies
  ansible.builtin.apt:
    name:
      - 'libpve-network-perl'
      - 'dnsmasq'
      - 'frr-pythontools'
      - 'wireguard-tools'
    state: present
  tags: networking

- name: Disable dnsmasq
  ansible.builtin.systemd:
    name: 'dnsmasq.service'
    state: stopped
    enabled: false
  tags: networking

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: networking

- name: Configure resolv.conf
  ansible.builtin.template:
    src: root/etc/resolv.conf
    dest: /etc/resolv.conf
    mode: '0644'
    owner: "root"
    group: "root"
  tags: networking
