"all":
  "hosts":
    "batuu":
      "ansible_host": "fd7a:115c:a1e0::1901:5864"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "onprem"
      "cloud_region": "tine"
      "nut_enabled": true
      "nut_host": "fe80::bf1e:8ac5:67c1:db1%vmbr0"
    "endor":
      "ansible_host": "fd7a:115c:a1e0::3b01:8154"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "onprem"
      "cloud_region": "tine"
      "nut_enabled": true
      "nut_host": "fe80::bf1e:8ac5:67c1:db1%vmbr0"
    "jakku":
      "ansible_host": "fd7a:115c:a1e0::301:c81b"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "onprem"
      "cloud_region": "tine"
      "nut_enabled": true
      "nut_host": "fe80::bf1e:8ac5:67c1:db1%vmbr0"
    "mustafar":
      "ansible_host": "fd7a:115c:a1e0::2601:d3d"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "onprem"
      "cloud_region": "jakob"
      "nut_enabled": false
      "nut_host": ""
    "nevaroo":
      "ansible_host": "fd7a:115c:a1e0::b301:3077"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "hetzner"
      "cloud_region": "germany"
      "nut_enabled": false
      "nut_host": ""
