"all":
  "hosts":
    "batuu":
      "ansible_host": "fd7a:115c:a1e0::1901:5864"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "onprem"
      "cloud_region": "tine"
      "features":
        "disable_network_offloading":
          "enabled": false
          "interfaces": []
        "nut":
          "enabled": true
          "host": "fe80::bf1e:8ac5:67c1:db1%vmbr0"
      "tailscale_ipv4": "100.110.88.100"
      "tailscale_ipv6": "fd7a:115c:a1e0::1901:5864"
    "endor":
      "ansible_host": "fd7a:115c:a1e0::3b01:8154"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "onprem"
      "cloud_region": "tine"
      "features":
        "disable_network_offloading":
          "enabled": false
          "interfaces": []
        "nut":
          "enabled": true
          "host": "fe80::bf1e:8ac5:67c1:db1%vmbr0"
      "tailscale_ipv4": "100.103.129.84"
      "tailscale_ipv6": "fd7a:115c:a1e0::3b01:8154"
    "jakku":
      "ansible_host": "fd7a:115c:a1e0::301:c81b"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "onprem"
      "cloud_region": "tine"
      "features":
        "disable_network_offloading":
          "enabled": true
          "interfaces":
          - "enp1s0"
          - "enp2s0"
        "nut":
          "enabled": true
          "host": "fe80::bf1e:8ac5:67c1:db1%vmbr0"
      "tailscale_ipv4": "100.67.200.27"
      "tailscale_ipv6": "fd7a:115c:a1e0::301:c81b"
    "mustafar":
      "ansible_host": "fd7a:115c:a1e0::2601:d3d"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "onprem"
      "cloud_region": "jakob"
      "features":
        "disable_network_offloading":
          "enabled": false
          "interfaces": []
        "nut":
          "enabled": false
          "host": ""
      "tailscale_ipv4": "100.99.13.61"
      "tailscale_ipv6": "fd7a:115c:a1e0::2601:d3d"
    "nevaroo":
      "ansible_host": "fd7a:115c:a1e0::b301:3077"
      "ansible_port": 22
      "ansible_user": "root"
      "cloud_provider": "hetzner"
      "cloud_region": "germany"
      "features":
        "disable_network_offloading":
          "enabled": true
          "interfaces":
          - "eno1"
        "nut":
          "enabled": false
          "host": ""
      "tailscale_ipv4": "100.82.48.119"
      "tailscale_ipv6": "fd7a:115c:a1e0::b301:3077"
