"network":
  "nodes":
    "batuu":
      "vmbr2":
        "ipv6":
          "address": "fd74:6a6f:3030:12::10/64"
          "subnet": ""
    "endor":
      "vmbr2":
        "ipv6":
          "address": "fd74:6a6f:3030:11::10/64"
          "subnet": ""
    "jakku":
      "vmbr2":
        "ipv6":
          "address": "fd74:6a6f:3030:13::10/64"
          "subnet": ""
    "nevaroo":
      "vmbr2":
        "ipv6":
          "address": "fd74:6a6f:3030:10::10/64"
          "subnet": ""
