firewall:
  - name: "ingress.tjo.cloud"
    host: "ingress.tjo.cloud"
    ports:
      - 22   # SSH
      - 25   # SMTP (explicit TLS => STARTTLS)
      - 80   # HTTP
      - 143  # IMAP (explicit TLS => STARTTLS)
      - 443  # HTTPS
      - 465  # ESMTP (implicit TLS)
      - 587  # ESMTP (explicit TLS => STARTTLS)
      - 993  # IMAP4 (implicit TLS)
      - 1337 # HTTP ingress.tjo.cloud healthcheck
      - 4190 # MANAGE SIEVE

# IPv4 and IPv6 addresses are from ZEROTIER.
bgp:
  batuu:
    asn: 65001
    ipv4: "172.26.158.117"
    ipv6: "fdb6:079f:73c6:3799:9099:939d:5a5e:8f57"
  jakku:
    asn: 65002
    ipv4: "172.26.2.34"
    ipv6: "fdb6:079f:73c6:3799:9099:936e:5fbd:e2e4"
  nevaroo:
    asn: 65003
    ipv4: "172.26.230.30"
    ipv6: "fdb6:079f:73c6:3799:9099:9366:d3f9:6a2c"
  mustafar:
    asn: 65004
    ipv4: "172.26.163.65"
    ipv6: "fdb6:079f:73c6:3799:9099:9332:0df3:7967"
  endor:
    asn: 65005
    ipv4: "172.26.201.97"
    ipv6: "fdb6:079f:73c6:3799:9099:9317:3d71:110d"
