"gateway":
  "hosts":
    "nevaroo":
      "ansible_become": true
      "ansible_host": "fd7a:115c:a1e0::b132:5a43"
      "ansible_port": 2222
      "ansible_user": "bine"
      "id": 10
      "lan":
        "internal":
          "prefix": "fd74:6a6f:0:10::/64"
        "public":
          "prefix": "2a01:4f8:120:7710::/64"
      "wireguard":
        "address": "fd74:6a6f:70::10/128"
"router":
  "hosts":
    "batuu":
      "ansible_become": true
      "ansible_host": "fd7a:115c:a1e0::7b32:6476"
      "ansible_port": 2222
      "ansible_user": "bine"
      "id": 12
      "lan":
        "internal":
          "prefix": "fd74:6a6f:0:12::/64"
        "public":
          "prefix": "2a01:4f8:120:7712::/64"
      "wireguard":
        "address": "fd74:6a6f:70::12/128"
    "endor":
      "ansible_become": true
      "ansible_host": "fd7a:115c:a1e0::5332:764"
      "ansible_port": 2222
      "ansible_user": "bine"
      "id": 11
      "lan":
        "internal":
          "prefix": "fd74:6a6f:0:11::/64"
        "public":
          "prefix": "2a01:4f8:120:7711::/64"
      "wireguard":
        "address": "fd74:6a6f:70::11/128"
    "jakku":
      "ansible_become": true
      "ansible_host": "fd7a:115c:a1e0::f632:d441"
      "ansible_port": 2222
      "ansible_user": "bine"
      "id": 13
      "lan":
        "internal":
          "prefix": "fd74:6a6f:0:13::/64"
        "public":
          "prefix": "2a01:4f8:120:7713::/64"
      "wireguard":
        "address": "fd74:6a6f:70::13/128"
