---
- name: Configure network.tjo.cloud
  hosts: all

  vars_files:
    - vars.yaml
    - vars.terraform.yaml
    - vars.terraform.secrets.yaml
    - vars.secrets.yaml

  handlers: []

  tasks:
    - name: Run defaults
      ansible.builtin.import_role:
        name: default
      vars:
        version: "{{ tjo_cloud_version }}"
        ssh_keys: "{{ tjo_cloud_admin_ssh_keys }}"
      tags: config-refresh

    - name: Install and Configure Observability
      ansible.builtin.import_tasks:
        file: tasks/observability.yaml

    - name: Install and Configure common things
      ansible.builtin.import_tasks:
        file: tasks/common.yaml
      tags: config-reload

    - name: Install and Configure router server
      ansible.builtin.import_tasks:
        file: tasks/router.yaml
      when: inventory_hostname in groups["router"]
      tags: config-reload

    - name: Install and Configure gateway server
      ansible.builtin.import_tasks:
        file: tasks/gateway.yaml
      when: inventory_hostname in groups["gateway"]
      tags: config-reload

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
