set dotenv-load

default:
  @just --list

apply:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu init
  tofu apply -exclude data.authentik_group.monitoring_publisher -exclude authentik_user.service_account -exclude authentik_token.service_account

destroy:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu destroy -target module.proxmox_node

destroy-only node:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu init
  tofu destroy --target 'module.proxmox_node["{{node}}"]'

dns-flush-cache domain:
  #!/usr/bin/env sh
  set -euo pipefail
  for node in $(cat vars.secrets.yaml | yq -r '.nodes | keys | .[]')
  do
    ssh bine@${node}-network-cloud-internal -p 2222 'unbound-control flush_negative' | ts ${node}
    ssh bine@${node}-network-cloud-internal -p 2222 'unbound-control flush_zone {{domain}}' | ts ${node}
  done

configure node tag="":
  #!/usr/bin/env sh
  cd {{source_directory()}}/ansible
  export VERSION=$(git describe --tags --always --dirty)
  TAGS=""; if [ -n "{{tag}}" ]; then TAGS="--tags {{tag}}"; fi
  ansible-playbook \
    --extra-vars "@{{source_directory()}}/../global.yaml" \
    --extra-vars "tjo_cloud_version=${VERSION}" \
    --inventory inventory.yaml \
    $TAGS \
    playbook.yaml --limit {{node}}

configure-all tag="":
  #!/usr/bin/env sh
  cd {{source_directory()}}/ansible
  export VERSION=$(git describe --tags --always --dirty)
  TAGS=""; if [ -n "{{tag}}" ]; then TAGS="--tags {{tag}}"; fi
  ansible-playbook \
    --extra-vars "@{{source_directory()}}/../global.yaml" \
    --extra-vars "tjo_cloud_version=${VERSION}" \
    --inventory inventory.yaml \
    $TAGS \
    playbook.yaml

ssh node:
  ssh bine@{{node}}-network-cloud-internal -p 2222
