metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 3
compression_level = 2

rpc_bind_addr = "[::]:3901"
#rpc_public_addr = "<this node's public IP>:3901"
rpc_public_addr_subnet = "10.100.0.0/16"
rpc_secret = "<RPC secret>"

[s3_api]
s3_region = "tjo-cloud"
api_bind_addr = "[::]:3900"
root_domain = "api.s3.tjo.cloud"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.s3.tjo.cloud"
index = "index.html"
