metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 3
consistency_mode = "consistent"
compression_level = 3

block_size = "1M"
block_ram_buffer_max = "1Gi"
block_max_concurrent_reads = 16

rpc_bind_addr = "[::]:3901"
rpc_public_addr_subnet = "10.0.0.0/16"

[s3_api]
s3_region = "tjo-cloud"
api_bind_addr = "[::]:3900"
root_domain = "api.s3.tjo.cloud"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.s3.tjo.cloud"
index = "index.html"
