- name: FIREWALL - Define internal zone
  ansible.posix.firewalld:
    source: '{{ item }}'
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ tjo_cloud_networks }}"
  tags: firewall

- name: FIREWALL - Allow HTTPS and STUN
  ansible.posix.firewalld:
    port: '{{ item }}'
    zone: public
    permanent: true
    immediate: true
    state: enabled
  loop:
    - '443/tcp'
    - '3478/udp'
  tags: firewall

- name: FIREWALL - Allow SSH
  ansible.posix.firewalld:
    service: ssh
    zone: '{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  loop:
    - 'internal'
    - 'public'
  tags: firewall
