- name: Install Caddy
  ansible.builtin.import_role:
    name: caddy

- name: Configure Caddy
  ansible.builtin.template:
    src: root/etc/caddy/Caddyfile
    dest: /etc/caddy/Caddyfile
    mode: '0600'
    owner: "caddy"
    group: "caddy"
  tags: config-reload
  notify: Restart caddy

- name: Instal podman
  ansible.builtin.apt:
    name:
      - podman
      - aardvark-dns
    state: present

- name: Set podman interface as trusted
  ansible.posix.firewalld:
    interface: podman1
    zone: trusted
    permanent: true
    immediate: true
    state: enabled
  tags: firewall

- name: Configure NAT64/DNS64 support
  ansible.posix.firewalld:
    rich_rule: rule family=ipv6 destination address="64:ff9b::/96" masquerade
    zone: public
    permanent: true
    immediate: true
    state: enabled
  tags: firewall

- name: Create netbird group
  ansible.builtin.group:
    name: "netbird"
    gid: 1010
    system: true
    state: present

- name: Create netbird User
  ansible.builtin.user:
    name: "netbird"
    uid: 1010
    group: "netbird"
    system: true
    state: present

- name: Create netbird directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0700"
    owner: "netbird"
    group: "netbird"
  loop:
    - "/etc/netbird"
    - "/srv/netbird/data"

- name: Copy netbird configs
  ansible.builtin.template:
    src: 'root{{ item }}'
    dest: '{{item}}'
    mode: '0640'
    owner: "netbird"
    group: "netbird"
  notify:
    - Restart netbird
  loop:
    - "/etc/netbird/config.yaml"
  tags: config-reload

- name: Copy network configuration
  ansible.builtin.template:
    src: 'root/etc/containers/systemd/{{ item }}'
    dest: '/etc/containers/systemd/{{ item }}'
    mode: '0600'
    owner: root
    group: root
  loop:
    - vpn.network
  tags: config-reload

- name: Copy container configuration
  ansible.builtin.template:
    src: 'root/etc/containers/systemd/{{ item }}.container'
    dest: '/etc/containers/systemd/{{ item }}.container'
    mode: '0600'
    owner: root
    group: root
  loop:
    - netbird-dashboard
    - netbird-server
  tags: config-reload
  register: container_configs

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  tags: config-reload

- name: Start containers
  ansible.builtin.systemd:
    name: "{{ item }}"
    # In case container config changed, restart it. Otherwise we only make sure it's running.
    state: "{{ container_configs.results | selectattr('item', 'equalto', item) | map(attribute='changed') | list | first | ternary('restarted', 'started') }}"
    enabled: true
  loop:
    - netbird-dashboard
    - netbird-server
  tags: config-reload
