"all":
  "hosts":
    "batuu-yellow-proxmox.s3.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f:0:12:be24:11ff:fe13:f275"
      "ansible_port": 2222
      "ansible_user": "bine"
      "garage_kind": "store"
      "garage_size": "800G"
      "garage_zone": "batuu"
      "provider": "proxmox"
    "endor-yellow-proxmox.s3.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f:0:11:be24:11ff:feb0:eeec"
      "ansible_port": 2222
      "ansible_user": "bine"
      "garage_kind": "store"
      "garage_size": "800G"
      "garage_zone": "endor"
      "provider": "proxmox"
    "jakku-yellow-proxmox.s3.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f:0:13:be24:11ff:fe77:49c5"
      "ansible_port": 2222
      "ansible_user": "bine"
      "garage_kind": "store"
      "garage_size": "800G"
      "garage_zone": "jakku"
      "provider": "proxmox"
    "pink-hetzner-cloud.s3.tjo.cloud":
      "ansible_become": true
      "ansible_host": "fd74:6a6f::90af:1eff:fe52:3884"
      "ansible_port": 2222
      "ansible_user": "bine"
      "garage_kind": "gateway"
      "garage_size": "0G"
      "garage_zone": "germany"
      "provider": "hetzner-cloud"
