router id 0.0.0.{{ cfg.id }};

protocol device {
}

protocol direct {
  ipv6;
}

##
# STATIC
##
protocol static {
  ipv6;

  {{ cfg.routes }}
}

##
# FILTERS
# We only manage BGP sourced routes using Bird.
##
function is_tjo_cloud_network() -> bool
{
  return net ~ [ {{ tjo_cloud_networks | product(["+"]) | map('join') | join(', ') }} ];
}
function is_vip_or_wireguard() -> bool
{
  return net ~ [ fd74:6a6f:53::/64+, fd74:6a6f:70::/64+ ];
}
filter route_export {
    if source !~ [ RTS_BGP, RTS_DEVICE, RTS_STATIC ] then reject;
    if source ~ [ RTS_DEVICE ] && !is_tjo_cloud_network() then reject;
    if dest ~ [ RTD_UNREACHABLE ] then reject;
    if is_vip_or_wireguard() then reject;
    accept;
}

##
# KERNEL
##
protocol kernel {
  scan time 10;
  persist;
  learn;

  kernel table 1000;

  ipv6 {
    export filter {
      if source !~ [ RTS_BGP ] then reject;
      accept;
    };
  };
}

##
# BFD
##
protocol bfd {
  accept ipv6 multihop;
  multihop {};
}

##
# BGP
##
protocol bgp dyn_wireguard {
  description "BGP for WIREGUARD";
  dynamic name "bgp_wg_dynamic";

  local port 179 as 650{{ cfg.id }};
  neighbor range fd74:6a6f:70::/64 external;
  source address {{ cfg.wireguard_address | ansible.utils.ipaddr('address') }};

  passive;
  multihop 2;
  graceful restart on;
  advertise hostname on;
  bfd graceful;

  ipv6 {
    export filter route_export;
    import all;
  };
}

{% for peer in cfg.peers %}
# Host: {{ peer.name }}
protocol bgp bgp_wg_cfg_{{ peer.name }} {
  description "BGP connection via WIREGURD to {{ peer.name }}";

  local port 179 as 650{{ id }};
  neighbor {{ peer.wireguard_address | ansible.utils.ipaddr('address') }} as 650{{ peer.id }};
  source address {{ cfg.wireguard_address | ansible.utils.ipaddr('address') }};

  multihop 2;
  graceful restart on;
  advertise hostname on;
  bfd graceful;

  ipv6 {
    export filter route_export;
    import all;
  };
}
{% endfor %}

##
# CUSTOM CONFIG
##
{{ cfg.bird_config_custom }}
