router id 0.0.0.{{ cfg.id }};

protocol device {
}

protocol direct {
  ipv6;
}

##
# STATIC
##
protocol static {
  ipv6;

  {{ cfg.routes | default("") }}
}

##
# FILTERS
# We only manage BGP sourced routes using Bird.
##
function is_tjo_cloud_network() -> bool
{
  return net ~ [ {{ tjo_cloud_networks | product(["+"]) | map('join') | join(', ') }} ];
}
function is_vip() -> bool
{
  return net ~ [ fd74:6a6f:3030:53::/64+ ];
}
filter route_export {
    if source !~ [ RTS_BGP, RTS_DEVICE, RTS_STATIC ] then reject;
    if source ~ [ RTS_DEVICE ] && !is_tjo_cloud_network() then reject;
    if dest ~ [ RTD_UNREACHABLE ] then reject;
    if is_vip() then reject;
    accept;
}

##
# KERNEL
##
protocol kernel {
  scan time 10;
  persist;
  learn;

  kernel table 1000;

  ipv6 {
    export filter {
      if source !~ [ RTS_BGP ] then reject;
      # FIXME: Change this once we go live!
      #accept;
      reject;
    };
  };
}

##
# BFD
##
protocol bfd {
  accept ipv6 multihop;
  multihop {};
}

##
# BGP
##
{% for peer in cfg.peers %}
# Host: {{ peer.name }}
protocol bgp bgp_wg_cfg_{{ peer.name | ansible.builtin.replace('-', '_') }} {
  description "BGP connection via WIREGURD to {{ peer.name }}";

  local port 179 as 650{{ cfg.id }};
  neighbor fe80:fd76:6a6f:3030:70::{{peer.id}} as 650{{ peer.id }};
  source address fe80:fd76:6a6f:3030:70::{{cfg.id}};
  interface "wg{{peer.id}}";

  graceful restart on;
  advertise hostname on;
  bfd graceful;

  ipv6 {
    export filter route_export;
    import all;
  };
}
{% endfor %}

##
# CUSTOM CONFIG
##
{{ cfg.bird_config_custom | default("") }}
