"all":
  "hosts":
    "purple-hetzner-cloud":
      "ansible_become": true
      "ansible_host": "116.202.11.24"
      "ansible_port": 2222
      "ansible_user": "bine"
      "wireguard":
        "address": "fd74:6a6f:3030:70::22/128"
        "id": 22
