server:
  tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

  num-threads: 1
  msg-cache-slabs: 1
  rrset-cache-slabs: 1
  infra-cache-slabs: 1
  key-cache-slabs: 1
  ratelimit-slabs: 1
  ip-ratelimit-slabs: 1

  use-syslog: yes
  statistics-interval: 0
  statistics-cumulative: no
  verbosity: 1
  extended-statistics: no

  interface-automatic: yes
  edns-buffer-size: 1232
  port: 53
  outgoing-port-permit: 10240-65535
  do-ip4: no
  do-ip6: yes

  harden-short-bufsize: yes
  harden-large-queries: yes
  harden-glue: yes
  use-caps-for-id: no

  msg-buffer-size: 32768
  outgoing-range: 1600
  num-queries-per-thread: 800
  outgoing-num-tcp: 50
  incoming-num-tcp: 50
  rrset-cache-size: 8192k
  msg-cache-size: 4096k
  stream-wait-size: 4096k
  key-cache-size: 4096k
  neg-cache-size: 1024k
  ratelimit-size: 1024k
  ip-ratelimit-size: 1024k
  infra-cache-numhosts: 8192

  dns64-prefix: 64:ff9b::/96
  module-config: "respip dns64 iterator"

  qname-minimisation: no
  prefetch: yes
  target-fetch-policy: "3 2 1 0 0"

  cache-min-ttl: 120
  cache-max-ttl: 72000
  cache-max-negative-ttl: 1000
  val-bogus-ttl: 300
  infra-host-ttl: 900

  hide-identity: yes
  hide-version: yes

  access-control: ::0/0 allow

forward-zone:
  name: internal.
  forward-addr: fd74:6a6f:3030:12:be24:11ff:fe8a:b5e6@53
  forward-first: yes
  forward-tls-upstream: no

forward-zone:
  name: arpa.
  forward-addr: fd74:6a6f:3030:12:be24:11ff:fe8a:b5e6@53
  forward-first: yes
  forward-tls-upstream: no

forward-zone:
  name: .
  forward-addr: 91.239.100.100@853#anycast.uncensoreddns.org
  forward-addr: 2001:67c:28a4::@853#anycast.uncensoreddns.org
  forward-addr: 89.233.43.71@853#unicast.uncensoreddns.org
  forward-addr: 2a01:3a0:53:53::@853#unicast.uncensoreddns.org
  forward-addr: 9.9.9.9@853#dns.quad9.net
  forward-addr: 149.112.112.112@853#dns.quad9.net
  forward-addr: 2620:fe::fe@853#dns.quad9.net
  forward-addr: 2620:fe::9@853#dns.quad9.net
  forward-first: yes
  forward-tls-upstream: yes

remote-control:
  control-enable: yes
  control-use-cert: no
  control-interface: 127.0.0.1
  control-interface: ::1
