"all":
  "hosts":
    "blue-hetzner-cloud":
      "ansible_become": true
      "ansible_host": "116.203.153.67"
      "ansible_port": 2222
      "ansible_user": "bine"
      "wireguard":
        "address": "fd74:6a6f:3030:70::21/128"
        "id": 21
