---
- name: Configure kamino.system.tjo.cloud
  hosts: all

  vars_files:
    - vars.yaml
    - vars.secrets.yaml
    - vars.terraform.secrets.yaml

  handlers:
    - name: Restart nut-exporter
      ansible.builtin.systemd:
        name: nut-exporter
        state: restarted
    - name: Restart nut-server
      ansible.builtin.systemd:
        name: nut-server
        state: restarted
    - name: Restart nut-monitor
      ansible.builtin.systemd:
        name: nut-monitor
        state: restarted

  tasks:
    - name: Create tjo.cloud directory
      ansible.builtin.file:
        state: directory
        path: "/etc/tjo.cloud"
        mode: "0700"
        owner: "root"
        group: "root"

    - name: Write metadata
      ansible.builtin.copy:
        dest: "/etc/tjo.cloud/meta.json"
        content: |
          {
            "cloud_provider": "onprem",
            "cloud_region": "rbpi",
            "service_account": {
              "password": "{{ tjo_cloud.credentials.password }}",
              "username": "{{ tjo_cloud.credentials.username }}"
            },
            "service_name": "kamino.system.tjo.cloud"
          }
        mode: "0600"
        owner: "root"
        group: "root"

    - name: Run defaults
      ansible.builtin.import_role:
        name: default
      vars:
        version: "{{ tjo_cloud_version }}"
        ssh_keys: "{{ tjo_cloud_admin_ssh_keys }}"
        configure_resolved: false

    - name: Install and Configure Observability
      ansible.builtin.import_tasks:
        file: tasks/observability.yaml

    - name: Install and Configure Firewall
      ansible.builtin.import_tasks:
        file: tasks/firewall.yaml

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Configure kamino
      ansible.builtin.include_tasks:
        file: tasks/kamino.yaml
