- name: Setup wireguard
  ansible.builtin.import_role:
    name: network-tjo-cloud-peer
    tasks_from: "setup"

- name: Setup peers
  ansible.builtin.set_fact:
    peers: |
      {{
        peers | default([]) + [{
          "name": item,
          "id": hostvars[item].id,
          "wireguard_endpoint_ipv4": hostvars[item].wireguard_endpoint_ipv4,
          "wireguard_endpoint_ipv6": hostvars[item].wireguard_endpoint_ipv6,
          "wireguard_address": hostvars[item].wireguard.address,
          "wireguard_public_key": hostvars[item].wireguard_public_key,
          "allowed_ips": [ hostvars[item].wireguard.address ] + tjo_cloud_networks
        }]
      }}
  loop: "{{ ansible_play_hosts | reject('equalto', inventory_hostname) }}"

- name: Setup Network Wireguard and BGP peer
  ansible.builtin.import_role:
    name: network-tjo-cloud-peer
    tasks_from: "configure"
  vars:
    cfg:
      id: "{{ id }}"
      wireguard_address: "{{ wireguard.address }}"
      wireguard_pre_shared_key: "{{ wireguard_pre_shared_key }}"
      peers: "{{ peers }}"
      routes: |
        {% if "gateway" in group_names %}
        route ::/0 via "eth0";
        {% endif %}
      bird_config_custom: |
        protocol bgp dyn_internal {
          description "BGP for INTERNAL";
          dynamic name "bgp_dyn_internal";

          local port 179 as 65000;
          neighbor range {{ lan.internal.prefix }} internal;

          passive;
          graceful restart on;
          advertise hostname on;

          ipv6 {
            export none;
            import all;
          };
        }

- name: Generate lan network configuration
  ansible.builtin.template:
    src: root/etc/systemd/network/00-lan.network
    dest: /etc/systemd/network/00-lan.network
    owner: "root"
    group: "systemd-network"
    mode: "640"

- name: Reaload network
  ansible.builtin.systemd:
    name: systemd-networkd
    state: reloaded

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-forwarding.conf

- name: FIREWALL - Define internal zone for lan
  ansible.posix.firewalld:
    interface: eth1
    zone: internal
    permanent: true
    immediate: true
    state: enabled

- name: FIREWALL - Enable forwarding in internal zone
  ansible.posix.firewalld:
    forward: true
    zone: internal
    permanent: true
    immediate: true
    state: enabled

- name: FIREWALL - Enable MSS MTU Clamping
  ansible.posix.firewalld:
    zone: internal
    rich_rule: rule tcp-mss-clamp value=pmtu
    permanent: true
    immediate: true
    state: enabled

- name: FIREWALL - DNS internal zone
  ansible.posix.firewalld:
    port: '{{ item }}'
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop:
    - "53/udp"
    - "53/tcp"

- name: Install unbound
  ansible.builtin.apt:
    name: unbound
    state: present

- name: Generate unbound configuration
  ansible.builtin.template:
    src: root/etc/unbound/unbound.conf.d/custom.conf
    dest: /etc/unbound/unbound.conf.d/custom.conf

- name: Reaload unbound
  ansible.builtin.systemd:
    name: unbound
    state: reloaded
    enabled: true
