- name: Install Jool
  ansible.builtin.apt:
    name:
      - jool-dkms
      - jool-tools
    state: present
    update_cache: yes

- name: Install yggdrasil
  ansible.builtin.apt:
    name:
      - yggdrasil
    state: present
    update_cache: yes
