- name: Install Jool
  ansible.builtin.apt:
    name:
      - jool-dkms
      - jool-tools
      - linux-headers-generic
    state: present

- name: Create /etc/jool
  ansible.builtin.file:
    state: directory
    path: "/etc/jool"

- name: Configure Jool
  ansible.builtin.template:
    src: root/etc/jool/jool.conf
    dest: /etc/jool/jool.conf

- name: Start Jool
  ansible.builtin.systemd:
    name: jool
    state: restarted
    enabled: true

- name: Install yggdrasil
  ansible.builtin.apt:
    name:
      - yggdrasil
    state: present
