- name: Reload ssh
  ansible.builtin.systemd:
    name: ssh
    state: reloaded

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
