- name: Install Zerotier
  ansible.builtin.include_role:
    name: zerotier

- name: Configure Zerotier
  ansible.builtin.shell: |
    systemctl stop zerotier-one
    echo "{{ tjo_cloud_metadata.zerotier.public_key }}" >/var/lib/zerotier-one/identity.public
    echo "{{ tjo_cloud_metadata.zerotier.private_key }}" >/var/lib/zerotier-one/identity.secret
    systemctl start zerotier-one
    sleep 5
    zerotier-cli join b6079f73c6379990
    sleep 5
    resolvectl dns ztyxa2r2sw fd74:6a6f:53::53 fd74:6a6f::1
  args:
    creates: /var/lib/zerotier-one/networks.d/b6079f73c6379990.conf

- name: Setup wireguard
  ansible.builtin.import_role:
    name: network-tjo-cloud-peer
    tasks_from: "setup"
  tags: config-reload

- name: Setup Network Wireguard and BGP peer
  ansible.builtin.import_role:
    name: network-tjo-cloud-peer
    tasks_from: "configure"
  vars:
    cfg:
      id: "{{ wireguard.id }}"
      wireguard_address: "{{ wireguard.address }}"
      wireguard_pre_shared_key: "{{ wireguard_pre_shared_key }}"
      peers:
        - name: "nevaroo"
          id: 10
          wireguard_endpoint: "2a01:4f8:120:7700:a8bb:ff:fe00:4536"
          wireguard_address: "fd74:6a6f:3030:70::10/128"
          wireguard_public_key: "pTz+6VD8OodLZz+88j8dYgSmE6F7kbpv704ISD2OADc="
          allowed_ips: '{{ tjo_cloud_networks }}'
        - name: "endor"
          id: 11
          wireguard_endpoint: "2001:2043:5d5d:d300:a8bb:ff:fe00:dbea"
          wireguard_address: "fd74:6a6f:3030:70::11/128"
          wireguard_public_key: "O/Z9bk0irnVB2weH7fm6Cl9Cl/Gc+zIkqf+Hh8dSEQQ="
          allowed_ips: '{{ tjo_cloud_networks }}'
        - name: "batuu"
          id: 12
          wireguard_endpoint: "2001:2043:5d5d:d300:a8bb:ff:fe00:f737"
          wireguard_address: "fd74:6a6f:3030:70::12/128"
          wireguard_public_key: "jPP4LbYC/QVW6rZxjru/C7XjyS7lyWDw8nIANpqTmhg="
          allowed_ips: '{{ tjo_cloud_networks }}'
        - name: "jakku"
          id: 13
          wireguard_endpoint: "2001:2043:5d5d:d300:a8bb:ff:fe00:8aaf"
          wireguard_address: "fd74:6a6f:3030:70::13/128"
          wireguard_public_key: "GAE2hslHVawcyEUOUYnpKfRI4KV73IM2tx50vdodEjc="
          allowed_ips: '{{ tjo_cloud_networks }}'
  tags: config-reload

- name: Refresh facts
  ansible.builtin.setup:
    gather_subset:
      - network

- name: Install valkey
  ansible.builtin.apt:
    name: valkey
    state: present

- name: Install Tar
  ansible.builtin.apt:
    name: tar
    state: present

- name: Download stalwart
  ansible.builtin.unarchive:
    src: https://github.com/stalwartlabs/stalwart/releases/download/{{ stalwart_version }}/stalwart-{{ ansible_architecture }}-unknown-linux-gnu.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install stalwart
  ansible.builtin.copy:
    src: /tmp/stalwart
    dest: /usr/local/bin/stalwart
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Download stalwart-cli
  ansible.builtin.unarchive:
    src: https://github.com/stalwartlabs/cli/releases/download/{{ stalwart_cli_version }}/stalwart-cli-{{ ansible_architecture }}-unknown-linux-gnu.tar.xz
    dest: /tmp
    remote_src: yes

- name: Install stalwart-cli
  ansible.builtin.copy:
    src: /tmp/stalwart-cli-{{ ansible_architecture }}-unknown-linux-gnu/stalwart-cli
    dest: /usr/local/bin/stalwart-cli
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Create stalwart group
  ansible.builtin.group:
    name: "stalwart"
    system: true
    state: present

- name: Create stalwart User
  ansible.builtin.user:
    name: "stalwart"
    group: "stalwart"
    system: true
    state: present

- name: Create Stalwart directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0700"
    owner: "stalwart"
    group: "stalwart"
  loop:
    - "/etc/stalwart"

- name: Copy Stalwart configs
  ansible.builtin.template:
    src: 'root{{ item }}'
    dest: '{{item}}'
    mode: '0640'
    owner: "stalwart"
    group: "stalwart"
  notify: Restart Stalwart
  loop:
    - "/etc/stalwart/config.json"
  tags: config-reload

- name: Create Stalwart systemd service file
  ansible.builtin.template:
    src: root/etc/systemd/system/stalwart.service
    dest: /etc/systemd/system/stalwart.service
    mode: '0644'
    owner: root
    group: root
  tags: config-reload
  notify: Restart Stalwart

- name: Enable and start stalwart
  ansible.builtin.systemd:
    name: stalwart
    state: started
    enabled: true
    daemon_reload: true
