default:
  @just --list

check:
  haproxy -c -f root/etc/haproxy/haproxy.cfg

secrets-encrypt:
  #!/usr/bin/env sh
  age --encrypt -R {{source_directory()}}/secrets.keys \
    secrets.env > secrets.env.encrypted

secrets-decrypt:
  #!/usr/bin/env sh
  age --decrypt \
    -i ${HOME}/.config/sops/age/keys.txt \
    secrets.env.encrypted > secrets.env

apply:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu init -upgrade
  tofu apply

destroy:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu  destroy

configure-all:
  #!/usr/bin/env sh
  set -eou pipefail

  pushd {{source_directory()}}/terraform > /dev/null
  NODES=$(tofu output -json | jq -r '.nodes.value[].name')
  popd > /dev/null

  for NODE in $NODES
  do
    just configure ${NODE} | ts ${NODE}
  done

configure node:
  #!/usr/bin/env sh
  set -eou pipefail

  pushd {{source_directory()}}/terraform > /dev/null
  IP=$(tofu output -json | jq -r '.nodes.value[] | select(.name=="{{node}}").ipv4')
  popd > /dev/null

  echo "== {{node}} at ${IP}"
  echo "=== Running configure.sh"
  cat configure.sh | ssh -o StrictHostKeyChecking=no -p 2222 root@${IP} 'bash -s'
