default:
  @just --list

apply:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu init -upgrade
  tofu apply

destroy:
  #!/usr/bin/env sh
  cd {{source_directory()}}/terraform
  tofu  destroy

configure:
  #!/usr/bin/env sh
  cd {{source_directory()}}/ansible
  ansible-playbook -i inventory.yaml playbook.yaml
