#log syslog all;
debug protocols all;

router id 0.0.0.{{ id }};

protocol device {
  scan time 10;
}

protocol direct {
  ipv6;
}

protocol static {
  ipv6;
}

protocol kernel {
  scan time 10;
  learn;
  persist;
  ipv6 {
    import all;
    export all;
  };
}

protocol kernel {
  persist;
  kernel table 1000;
  ipv6 {
    table tjocloudbgp;
    export all;
  };
}


##
# FILTERS
# We only manage BGP sourced routes using Bird.
##
filter route_export {
    if source !~ [ RTS_BGP ] then reject;
    else accept;
}

##
# BGP
##
{% for host in (ansible_play_hosts | reject('equalto', inventory_hostname)) %}
# Host: {{ host }}
protocol bgp uplink_peer_{{ host }} {
  description "BGP connection to {{ host }}";

  local as 650{{ id }};
  neighbor {{ hostvars[host].wireguard.address | ansible.utils.ipaddr('address') }} as 650{{ hostvars[host].id }};

  multihop 2;
  graceful restart on;
  advertise hostname on;

  ipv6 {
    table tjocloudbgp;
    export filter route_export;
    import all;
  };
}

{% endfor %}

protocol bgp dyn_wireguard {
  description "BGP for WIREGUARD";
  dynamic name "bgp_dyn_wireguard";

  local port 179 as 650{{ id }};
  neighbor range fd74:6a6f:70::/64 external;

  passive;
  graceful restart on;
  advertise hostname on;

  ipv6 {
    export filter route_export;
    import all;
  };
}

protocol bgp dyn_internal {
  description "BGP for INTERNAL";
  dynamic name "bgp_dyn_internal";

  local port 179 as 65000;
  neighbor range {{ lan.internal.prefix}} internal;

  passive;
  graceful restart on;
  advertise hostname on;

  rr client;

  ipv6 {
    export filter route_export;
    import all;
  };
}
